[package]
name = "weather_ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
noise = "0.9.0"
rand = {version="0.9.2", features=["thread_rng"]}
rand_core = "0.6.4"
russh = "0.56.0"
tokio = {version="1.49.0", features=["full"]}
